name: Comment on Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          DATABASE_URL: postgresql://postgres.dntvridtsvpckqpstzvm:Oussema-cherni2002@aws-0-eu-west-3.pooler.supabase.com:6543/postgres
        run: |
          python bot.py --pr_number "${{ github.event.pull_request.number }}" --repo "${{ github.repository }}"

