name: SonarCloud

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run SonarCloud analysis
        uses: SonarSource/sonarqube-scan-action@v4
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: Oussema14367939_pr-bot
          SONAR_ORGANIZATION: Oussema14367939
